import { montserrat } from "@/assets/fonts/fonts";
import Header from "@/components/Header/Header";
import { SpinnerProvider } from "@/components/Spinner";
import QueryProviderWrapper from "@/components/wrappers/QueryProviderWrapper";
import type { Metadata } from "next";
import { Inter, Noto_Sans_KR } from "next/font/google";
import "./globals.css";

const inter = Inter({
    variable: "--inter",
    subsets: ["latin"],
});
const notoSansKR = Noto_Sans_KR({
    variable: "--noto-sans-kr",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Dataracy",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${inter.variable} ${montserrat.variable} ${notoSansKR.variable} font-nsKR min-w-[1200px]`}>
                <QueryProviderWrapper>
                    <SpinnerProvider>
                        <Header />
                        {children}
                        {/* <Footer /> */}
                    </SpinnerProvider>
                </QueryProviderWrapper>
            </body>
        </html>
    );
}
