import { montserrat } from "@/assets/fonts/fonts";
import Footer from "@/components/Footer/Footer";
import Header from "@/components/Header/Header";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
    variable: "--inter",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Dataracy",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${inter.variable} ${montserrat.variable} font-inter`}>
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    );
}
